### ISSUE TITLE
Improved support with old color palette 

### ISSUE THREAD

**Issue by mkstix6** [ctf0/Seti_UX#11]
Preference thing.
I like that the highlighting support is better, of course, but I'm not sold on the new color palette. Is there a way to get the old palette back?

**Comment by ctf0** [comment]
u mean the original port ?, if yes then u will need to make the changes ur self as i dont have time to report this with the old colors palette.

**Comment by mkstix6** [comment]
Ok, sure.

Perhaps you can still help.
The reason I installed SETI_UX is because the SETI_UI update removed the old palette I was using.
Do you know how to get the original port of the palette?
Does it still exist?
The SETI_UI home page now links to SETI_UX.

**Comment by ctf0** [comment]
sure, check this
https://github.com/ctf0/Seti_ST3/issues/207
and here are the old schemes
https://github.com/ctf0/Seti_ST3/tree/Mods/Scheme

**Comment by mkstix6** [comment]
Thanks for the help @ctf0.
And thanks for the hard work in the past porting SETI.

**Comment by ctf0** [comment]
np, its all good, glad u like it :smile_cat:
