### ISSUE TITLE
 add explanatory note in css files appear problem

### ISSUE THREAD

**Issue by zhiqiang21** [ctf0/Seti_UX#12]
when i use this theme  add explanatory note in css files appear problem.

 explanatory note and origin note not different.

![qq20160215-0](https://cloud.githubusercontent.com/assets/3990411/13039662/eb7cb216-d3dc-11e5-9c1d-a9056ed624b5.png)

**Comment by ctf0** [comment]
am sorry but what exactly is the issue ?, from what i see from the ss, the highlighting is working as intended.

**Comment by zhiqiang21** [comment]
thank you   , i know you  mean!

**Comment by ctf0** [comment]
so all good, close the ticket ?
