### ISSUE TITLE
Better Javascript highlighting

### ISSUE THREAD

**Issue by NIPanag** [ctf0/Seti_UX#13]
Hello, first of all thank you for your great work.
I chanced upon this project and I think it would be fantastic if Seti could work with it by design.
https://github.com/bathos/Ecmascript-Sublime

From it's readme

> A sublime-syntax language definition for Ecmascript / Javascript / ES6 / ES2015 / Babel or what have you.

Here's a screenshot showing off it's capabilities.
![](https://raw.githubusercontent.com/bathos/Ecmascript-Sublime/master/example-barf.png)

**Comment by ctf0** [comment]
thanx for the suggest, but it seems it still in the beta phase, however i was thinking of changing from js next to babel but again both still not updated yet to the new syntax def, so will wait for a now till any gets updated.

**Comment by ctf0** [comment]
@NIPanag do u still need this ?

**Comment by NIPanag** [comment]
@ctf0 Hey, thanks for asking.
I don't need this anymore, no. I've since moved to typescript and as of a few days ago to atom.
I'll go ahead and close this issue.
