### ISSUE TITLE
Strings not correctly highlighted in C/C++, Java, etc.

### ISSUE THREAD

**Issue by polmes** [ctf0/Seti_UX#14]
Ok, so I just realized (as per the screenshot below), strings &mdash;both 'single quote' and "double quote"&mdash; are not getting correctly highlighted in "non-supported" languages, like C/C++, Java, etc.

It looks like the issue was spotted and fixed over a year ago by @LinuCC in #4, but the workaround was then removed in 928f881, and the problem seems to persist today in both the latest stable release (v2.5.1) and also in the latest code cloned from the repo.

Any reason behind that change?

![seti_quotes](https://cloud.githubusercontent.com/assets/4205413/14044394/613512a6-f290-11e5-8b98-c447922190be.png)

**PS** Yeah, I know, I forgot to use the `std` namespace. Nevermind.

**Comment by ctf0** [comment]
am sorry i cant help as i don't use either of those languages, also this could be related to the new syntax added in the latest versions of ST.

**Comment by polmes** [comment]
Yeah, I really don't know what the root of the problem might be. Having said that, I just tested re-adding something like 73709be (in ST 3103) and it looks like that would fix the problem... However, I haven't been able to check whether it breaks anything in other "supported" languages, as I don't use all of them either.

**Comment by ctf0** [comment]
this make us 2 :monkey_face:
