### ISSUE TITLE
Popup styling

### ISSUE THREAD

**Issue by buildersbrewery** [ctf0/Seti_UX#16]
https://www.sublimetext.com/3dev

> Build 3116
> * Color Schemes: Added popupCss key, for defining default popup style sheets.

**Comment by ctf0** [comment]
have no idea and the last dev is 3113

**Comment by buildersbrewery** [comment]
Then he pulled it during the last couple of minutes.

**Comment by ctf0** [comment]
will keep an eye out 👀

**Comment by buildersbrewery** [comment]
Build 3117 will be out shortly according to:

* https://forum.sublimetext.com/t/dev-build-3116/21148/12

**Comment by ctf0** [comment]
keep me posted 👍

**Comment by buildersbrewery** [comment]
This was in `Monokai.tmTheme`:

```xml
<dict>
    <key>settings</key>
    <array>
        <dict>
            <key>settings</key>
            <dict>
              <key>popupCss</key>
              <string><![CDATA[
    html {
        background-color: #404238;
        color: #F8F8F2;
    }
    a {
        color: #66D9EF;
    }
    .error, .deleted {
        color: #F92672;
    }
    .success, .inserted {
        color: #A6E22E;
    }
    .warning, .modified {
        color: #FD971F;
    }
              ]]></string>

...
```

**Comment by ctf0** [comment]
will be added asap.

**Comment by ctf0** [comment]
@buildersbrewery there is an issue with seti for some reason, however install the latest dev of ST and u will get  abit better popup clring
