### ISSUE TITLE
Disable comment highlighting

### ISSUE THREAD

**Issue by haitran14** [ctf0/Seti_UX#17]
Your color scheme is amazing :+1: 
However, can you add an option of disabling comments highlighting? As for me, I don't really enjoy it.
Thanks :).

**Comment by ctf0** [comment]
sadly schemes doesnt have the option to disable or enable anything , i basically either include the scope of not :(.

**Comment by brunowoo** [comment]
Would you be able to give me a hint on what I should edit to disable these? It seems that in yaml files empty lines are also highlighted, which I find a bit annoying personally.

**Comment by ctf0** [comment]
@brunowoo can u open a new issue for this ?
