### ISSUE TITLE
Better haskell syntax support

### ISSUE THREAD

**Issue by reygoch** [ctf0/Seti_UX#18]
Hi, is it possible to get better Haskell syntax support? Current one is kind of lacking. There is SublimeHaskell package that gives a nice syntax support for Haskell but it's kind of ugly :D

**Comment by ctf0** [comment]
i found a the schemes it use https://github.com/SublimeHaskell/SublimeHaskell/tree/master/Themes , maybe you can copy the hl from them and add to seti under new section then change it  to go along with the rest of seti ?

u can use https://packagecontrol.io/packages/ColorHelper to make it easier to you to view the colors in the scheme file.

**Comment by reygoch** [comment]
Is there a list of all colors used in Seti_UX?

**Comment by ctf0** [comment]
no, not really but am working on extracting all through https://packagecontrol.io/packages/Huely%20Palette%20Extractor 

for now you can use adifferent syntax as ref and use https://packagecontrol.io/packages/ScopeHunter to easily get the scope colors
