### ISSUE TITLE
Completely unrelated

### ISSUE THREAD

**Issue by ginfuru** [ctf0/Seti_UX#19]
Hey sorry for posting an issue for unrelated items, but figured I'd share my iTerm2 color scheme https://github.com/ginfuru/iTerm-RainCoat

**Comment by ctf0** [comment]
well fuck yeah, wanna add it to seti rdme ?

**Comment by ginfuru** [comment]
Yeah i can do that.

**Comment by ctf0** [comment]
go for it then and send me the PR :+1:
