### ISSUE TITLE
Strings too dark in python

### ISSUE THREAD

**Issue by Dopamine63** [ctf0/Seti_UX#21]
Pretty much what the title says

Here is a screenshot as an example.
![screen shot 2016-12-20 at 15 38 53](https://cloud.githubusercontent.com/assets/11146784/21363132/9f4bf6a6-c6eb-11e6-8eae-3cd56eb9e7b9.png)

**Comment by ctf0** [comment]
updated, plz manually install the latest commit and see if it fix ur issue

**Comment by Dopamine63** [comment]
Yes its fixed 👍 
![screen shot 2016-12-20 at 20 03 49](https://cloud.githubusercontent.com/assets/11146784/21364054/7b650350-c6ef-11e6-81b0-94dfd5a6ec50.png)

**Comment by ctf0** [comment]
sweet
