### ISSUE TITLE
Enhancement: JSON level coloring

### ISSUE THREAD

**Issue by bfelder** [ctf0/Seti_UX#24]
The color scheme Monkai JSON+ offers the unique feature of highlighting nesting level with color.
Have a look here: [Monokai JSON+](https://packagecontrol.io/packages/Monokai%20JSON%2B)

I feel Seti UX a similar coloring would be a good fit to Seti UX, which is a vibrant theme in itself.
Such coloring would undoubtedly enhance the comprehensibility of JSON, therefore being useful to the user.

**Comment by ctf0** [comment]
seti used to have this, but with latest updates in json, it totaly blowen up, so i removed all and kept only the first level
![json](https://user-images.githubusercontent.com/7388088/28502328-2a554be6-6ff0-11e7-9264-9dbef2e28145.png)

**Comment by bfelder** [comment]
Ah, so sad. You got good taste to include it in the first place. Any plans to re-include it. Maybe with hint from the Monokai JSON+ theme I have mentioned?

**Comment by ctf0** [comment]
i doubt `Monokai JSON+` is still working with the latest version of ST, if you want to give it a try ? go for it.

**Comment by bfelder** [comment]
No. Not in the foreseeable future. Yet, there is another python addition I like to contribute to Seti UX. More on this in a well from now.
