### ISSUE TITLE
Simplify Color Palette

### ISSUE THREAD

**Issue by pykong** [ctf0/Seti_UX#34]
There are currently **163** (!) distinct colors in Seti_UX.
That high number makes maintenance and extension of the color scheme difficult.
Also, many colors look so similar that they are not visually discernable, which goes against their very purpose.

I have reduced the original palette down to 100 colors, by eliminating those that I could not readily tell apart:

https://pastebin.com/nA2JZvyp

@ctf0 Could you please have a look into those and tell me if you approve the new palette?
Or make according changes?

I will then go on to process our `.tmTheme` to include only those colors.

**Comment by ctf0** [comment]
i honestly cant tell unless i have it applied to the scheme, so go a ahead and apply the changes and will refine it after

**Comment by pykong** [comment]
@ctf0 Sure, find it here:
https://pastebin.com/qSaYfBLv
(My git is currently not working.)

Important is to get us a consistent color palette, because this will instruct any further improvements and adaptions of this great color scheme. I for example would like to just chose from such palette instead of just randomly introducing new colors as I seem fit. 

I could even write a Travis test for it to keep new contributions on line with that palette.

**Comment by ctf0** [comment]
for some reason the one on pastebin is 10kb bigger, is it possible to apply the changes to the latest commit ?

**Comment by pykong** [comment]
@ctf0 Hey, sorry for the big delay. I have been busy programming the newest version of SublimeLinter in the past couple of month and needed to do a lot of stuff for the beta.

Yeah, I can apply the changes directly. Will, push those to a separate branch so you can safely check em out, bro.

**Comment by ctf0** [comment]
will close this in favour of the PR.

**Comment by pykong** [comment]
I tend to keep issues open and let them close via a PR hook.
You can try it out, just put 
```
Fixes: #ISSUE_NUMBER
```
Into the PR's comment and GitHub will automatically close the issue once the PR got closed/merged.
This is a really convenient to keep a repo tidy.
