### ISSUE TITLE
Create collection of scheme tools.

### ISSUE THREAD

**Issue by pykong** [ctf0/Seti_UX#39]
We use three tools to help us adapt and extend Seti_UX. 
- `hex_tractor.py` (extracting color palette from theme file)
- `hex_rounder` (reduce color palette of file and switch case of hex strings)
- `color_visualizer.js` (visualizing and editing color palette)

It would be great if we collected them into a single place.
Either a new separate repo or as sub_dir of Seti_UX.

**Comment by ctf0** [comment]
create a new branch and send a PR
