### ISSUE TITLE
Convert to ".sublime-color-scheme"

### ISSUE THREAD

**Issue by pykong** [ctf0/Seti_UX#40]
The new scheme format comes with many improvements.
Among those is the ability to declare variables, which greatly simplify working on a color scheme.

![image](https://user-images.githubusercontent.com/20211140/34633727-5038c80e-f27e-11e7-99d5-55513a885ef3.png)

We may consider freezing the old `.tmTheme` file and continue development solely in the new format.
Once the new format hits the stable branch the old `.tmTheme` can be disposed off.

ST comes with an inbuilt way converter which right does not work on `Seti.tmTheme` because of an error.
If we decide to switch formats we would make use of this conversion function, once that issue is solved.

**Comment by pykong** [comment]
@ctf0 Have you ever tried to convert `Seti_UX`?
Sublime Text's inbuilt command throws an exception related to an invalid hex value when I attempt to perform this conversion (*See console output*). 
I do not get the same error with other schemes tested.

![image](https://user-images.githubusercontent.com/20211140/37432466-b84859de-27d8-11e8-9694-f358a25a2cf4.png)

**Comment by ctf0** [comment]
am not sure where is that cmnd came from

**Comment by pykong** [comment]
OK. You need to open and focus the `Seti.tmTheme` file.
The search command `Convert Color Scheme` via command palette.

**Comment by ctf0** [comment]
can u show me a gif cuz i really cant find anything like that

**Comment by pykong** [comment]
It requires ST >= 3154.
I do not think a gif will convey any more information than I have given.

Here is another screenshot:
![image](https://user-images.githubusercontent.com/20211140/37487200-25d3f0e0-2891-11e8-8095-d6475e9aaeed.png)

**Comment by ctf0** [comment]
![screen shot 2018-03-15 at 9 45 22 pm](https://user-images.githubusercontent.com/7388088/37487446-409fb07c-289a-11e8-8702-c9238a26a401.jpg)

**Comment by pykong** [comment]
Did you focus `Seti.tmTheme`? I can not see it in the background.

**Comment by ctf0** [comment]
u meant opening the scheme then open the quick panel, i trid now and i get the error
```
ValueError: Invalid hex color 
```

which am not sure why, but i think there might be more than one reason, for a start try to remove all the comments and try again

**Comment by pykong** [comment]
Congrats. You found the command!
Indeed, this is the same error that I am getting.
I thought you may have an idea what the reason is.

I am not sure it is the comment because ST's json system handles them (unlike the `json` module from py stdlib).

**Comment by ctf0** [comment]
i honestly not sure what exactly is cuzing this but i've tried like 5 times b4 to format the scheme into something semantic like every other schemes out there but because of the picky scopes i have it always fails 😢

**Comment by ctf0** [comment]
i would say that maybe we can focus first of adding the support to the missing langs then we can tackle this later
