### ISSUE TITLE
Problem with Diff color

### ISSUE THREAD

**Issue by louim** [ctf0/Seti_UX#45]
Hey! 
Diff used to look like this: 
![capture d ecran 2018-03-22 a 12 08 02](https://user-images.githubusercontent.com/923718/37782649-c79e4dd4-2dc9-11e8-953b-a633d9e47985.png)

But now they look like this:
![capture d ecran 2018-03-22 a 12 08 58](https://user-images.githubusercontent.com/923718/37782681-de178c4c-2dc9-11e8-83cd-822c66801701.png)

I'm a little bit confused, since the Repo says that the last commit is from 22 Sep 2017, but the files were modified 7 days ago.

I'm not versed enough in Sublime themes to know how to fix the problem. Do you have an idea what changes could have caused this?

**Comment by ctf0** [comment]
np,i will fix it, btw do u have something to test with ?

**Comment by louim** [comment]
Paste [this](https://github.com/ctf0/Seti_UX/commit/73ae84ae8c059abf7750f824874d216a1717f250.diff) in a new sublime file to test. Select `diff` as syntax if it doesn't automatically.

**Comment by ctf0** [comment]
yea i understand, thats mostly because am refactoring the colors pallet of the scheme so its easier to maintain , also what version of ST r u using ? and isnt it possible to send the same text in the ss above ?

**Comment by louim** [comment]
I'm running `Dev Channel, Build 3157` on OS X. The screenshot is a part of a rather large diff from a private project. I would prefer not to put it on the internet unless it's absolutely necessary.

**Comment by louim** [comment]
```diff
diff --git a/app/services/import_users.rb b/app/services/import_users.rb
index 343446424..1bd696438 100644
--- a/app/services/import_users.rb
+++ b/app/services/import_users.rb
@@ -1,7 +1,7 @@
 # frozen_string_literal: true

 class ImportUsers
-  BASE_HEADERS = %w[first_name last_name email occurrence_ids country_code state_code
+  BASE_HEADERS = %w[first_name last_name email locale occurrence_ids country_code state_code
                     taxon_ids invite_message invite_skip identity bio].freeze

   # Expect a CSV with headers included in BASE_HEADERS or keys in user profile schema.
```

**Comment by ctf0** [comment]
thanx, i will try to push the fix today

**Comment by ctf0** [comment]
try the latest commit, tell me if u want the bg color back

**Comment by louim** [comment]
Looking good to me! No need to bring back the background color, since it was not really different from the normal brackground, and I see you're trying to reduce the number of colors.

**Comment by ctf0** [comment]
awesome.
