### ISSUE TITLE
Remove Comment highlighting. 

### ISSUE THREAD

**Issue by OpticGenius** [ctf0/Seti_UX#46]
Hi. I really like this theme, but the comment highlighting is very distracting. How can I disable it?

![screenshot from 2018-04-03 19-27-44](https://user-images.githubusercontent.com/20082136/38241348-48ba70f0-3775-11e8-9590-7bfb9c8d50fc.png)

**Comment by ctf0** [comment]
search for comment in https://github.com/ctf0/Seti_UX/blob/master/Seti.tmTheme and comment-out/remove any background key like https://github.com/ctf0/Seti_UX/blob/da0484a27452ef33b0a27acae52cacbb40b40466/Seti.tmTheme#L174-L175
