### ISSUE TITLE
Markdown Syntax Highlighting Issue

### ISSUE THREAD

**Issue by nicholaelaw** [ctf0/Seti_UX#6]
Just installed Seti_UI and Seti_UX. Feels like I've not been using ST properly. Love every inch.

But I discovered a small issue in markdown syntax highlighting. If preceded by an HTML `<script></script>` block, syntax highlighting stops for all markdown texts that follows. JS and HTML highlighting is unaffected, just md.

The screenshot:

![setiux-md-highlighting-problem](https://cloud.githubusercontent.com/assets/10719482/9702546/e7ae2858-5494-11e5-97a6-12a4fd6fa1cf.jpg)

Thanks again for producing such a looky theme.

**Comment by ctf0** [comment]
first. glad you liked it, i do appreciate the kind words,
second. actually this is the first time i see scripts tag are used in MD however i think what you are after is 
```js
$(non-existent-js)

**Comment by nicholaelaw** [comment]
Ahhh I should have explained my use case. Sorry for the confusion. I have a little blog on GitHub Pages built using Jekyll. I write articles in `markdown`, and Jekyll does the processing and renders them into web pages.

Occasionally I needed to insert a component like [`List.js`](http://www.listjs.com/) into the article, and some component requires a small script on the page to initialize. 

So yeah, I hope you can see that I did not mean to write a code block. I'm essentially writing web pages using a mix of md/html/css/js. And the highlighting issue pops out because I didn't encounter it with ST's default color scheme.

**Comment by nicholaelaw** [comment]
Oh another thing to note is that since GitHub Pages does not support GFM by default, I never learned to use the <code>```html</code> thing.

**Comment by ctf0** [comment]
can you send me some demo code to test with and also what is the scheme you use that gives you the correct coloring.

**Comment by nicholaelaw** [comment]
Sorry for the late reply, here's the source of one of my pages: http://pastebin.com/5719GSw7

Here's how it looks like on my setup, notice the second title "How to" is not highlighted any more.

<img width="1139" alt="demo-highlight-issue" src="https://cloud.githubusercontent.com/assets/10719482/9753418/093eebe0-56ef-11e5-93d7-0a956689fde0.png">

I must apologize and correct my previous claim about default color scheme being fine. I checked again and realized the reason I did not notice anything before switching theme: ST's default highlighting for Markdown is almost nothing is highlighted. Here's what the code looks like in ST2's default highlighting (I've only recently switched to ST3).

<img width="1017" alt="demo-highlight-issue-st2" src="https://cloud.githubusercontent.com/assets/10719482/9753530/985f49c2-56f0-11e5-8d59-3bc831df86b0.png">

All Markdown text are white, so my brain is tricked into believing they are properly handled. Thanks for the suggestion, I've tried both Markdown Extended and Markdown Editing but didn't find them appealing. For me Markdown is just an easy way to prepare a webpage. So ST default is good enough for me.

But like I said, this syntax highlighting thing really isn't a big deal. I'm pretty happy with SetiUI/UX even if you decide this is outside normal use and do nothing about it. Have a good day.

**Comment by ctf0** [comment]
no its okay, we can find a solution for that but are you sure that writing tags within MD without any adding something like the quotes or something is right ?

**Comment by nicholaelaw** [comment]
I'm sure. I'm writing a mixture of markdown, html and a little js within the md file. It's not quotes or code blocks.

**Comment by ctf0** [comment]
right now the only solution is to have the scripts inside either 
```html
<script>
$bla
</script>
```
or
```js
$bla
```
