### ISSUE TITLE
Stopped working in Makefiles

### ISSUE THREAD

**Issue by kgizdov** [ctf0/Seti_UX#7]
Not sure why, but it updated and now targets in Makefiles are not highlighted, but were previously.

**Comment by ctf0** [comment]
can u send me something to test with as u never used that syntax ?

**Comment by kgizdov** [comment]
Sure.
This is how Seti_UX looks now. Previously it would highlight the 'target' file (file at the begging of the line followed immediately by a colon), but not any more. Variables are set by putting '=' after them. Comments are given by '#' if it matters.
![Seti_UX](http://imgur.com/vCltP2a.png)

Here's a sample of another theme that shows some elements.
![Neon](http://imgur.com/7i1I6Wc.png)

**Comment by ctf0** [comment]
great, can u now send me the code to test with and add the HL for it ?

**Comment by kgizdov** [comment]
[Here's one](https://pastebin.com/LZLjyFYB)

**Comment by ctf0** [comment]
check the last update and tell me if its working okay with u.

**Comment by kgizdov** [comment]
all good
